const state = { events: [], selected: null, editPayload: '', paused: false, page: 0, pageSize: 100, total: 0, pending: [], renderTimer: 0, filters: { search: '', direction: '', network: '', host: '', protocol: '', status: '', excludeCommand: '' } };
const view = document.querySelector('#view');
const detail = document.querySelector('#detail');
const status = document.querySelector('#status');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const pretty = value => typeof value === 'string' ? value : JSON.stringify(value ?? '', null, 2);
function network(record) { return record.kind === 'websocket-frame' || record.kind === 'websocket' ? 'WebSocket' : record.kind?.startsWith('http') ? 'HTTP' : record.kind || '未知'; }
function frame(record) { return record.game_frame || {}; }
function protocol(record) { const f = frame(record); return f.protocol_category || (record.game_frame ? 'sproto' : record.protocol || ''); }
function protocolStatusKind(record) { const f = frame(record); if (record.kind !== 'websocket-frame') return record.protocol ? 'success' : 'failure'; const decode = String(f.decode_status || '').toLowerCase(); const schema = String(f.schema_status || '').toLowerCase(); const failed = !decode || decode.includes('required') || decode.includes('unknown') || decode.includes('unrecognized') || decode.includes('encrypted-or-unknown') || schema.includes('unavailable') || schema.includes('not-found'); return failed ? 'failure' : 'success'; }
function protocolStatus(record) { if (protocolStatusKind(record) === 'success') return '解码成功'; const f = frame(record); const error = [f.decode_status, f.schema_status, record.protocol].filter(Boolean).join(' · ') || '未识别协议'; return `解码失败：${error}`; }
function searchText(record) { const f = frame(record); return [record.host, record.url, record.command_name, commandName(record), f.command_name, f.command, protocol(record), protocolStatus(record)].join(' ').toLowerCase(); }
function commandKey(record) { const f = frame(record); return f.command ? String(f.command) : commandName(record); }
function commandLabel(record) { const f = frame(record); return f.command ? `${commandName(record)} · ${f.command}` : commandName(record); }
function values(fn) { return [...new Set(state.events.map(fn).filter(Boolean))].sort(); }
function filteredRows() { const f = state.filters; return state.events.filter(x => network(x) !== 'HTTP' && (!f.search || searchText(x).includes(f.search.toLowerCase())) && (!f.direction || x.direction === f.direction) && (!f.network || network(x) === f.network) && (!f.host || x.host === f.host) && (!f.protocol || protocol(x) === f.protocol) && (!f.status || protocolStatusKind(x) === f.status) && (!f.excludeCommand || commandKey(x) !== f.excludeCommand)); }
async function loadPage(page = 0) { const response = await fetch(`/api/history?page=${page}&size=${state.pageSize}`); const data = await response.json(); state.page = data.page; state.total = data.total; state.events = data.items || []; if (!state.selected || !state.events.some(x => x.id === state.selected.id)) { state.selected = null; state.editPayload = ''; } render(); }
function refreshFilters() { [['direction', '方向', x => x.direction], ['network', '网络类型', network], ['host', '主机', x => x.host], ['protocol', '协议类型', protocol]].forEach(([key, name, getter]) => { const select = document.querySelector(`[data-filter="${key}"]`); const current = state.filters[key]; select.innerHTML = `<option value="">全部${name}</option>${values(getter).map(v => `<option value="${esc(v)}">${esc(v)}</option>`).join('')}`; select.value = current; }); document.querySelector('#filter-status').value = state.filters.status; const exclude = document.querySelector('#filter-exclude-command'); const commands = new Map(); state.events.forEach(record => { const key = commandKey(record); if (key && commandName(record) !== '未识别') commands.set(key, commandLabel(record)); }); exclude.innerHTML = `<option value="">不排除命令</option>${[...commands.entries()].sort((a, b) => a[1].localeCompare(b[1], 'zh-CN')).map(([key, label]) => `<option value="${esc(key)}">${esc(label)}</option>`).join('')}`; exclude.value = state.filters.excludeCommand; }
function pager() { const pages = Math.max(1, Math.ceil(state.total / state.pageSize)); return `<div class="pager"><button id="newer" ${state.page ? '' : 'disabled'}>较新</button><span>第 ${state.page + 1} / ${pages} 页 · 共 ${state.total} 条 · 每页 ${state.pageSize} 条</span><button id="older" ${state.page >= pages - 1 ? 'disabled' : ''}>较旧</button></div>`; }
function commandName(record) { const f = frame(record); return f.command_name || (f.command ? `command_${f.command}` : '未识别'); }
function table() { const rows = filteredRows().slice().reverse(); if (!rows.length) return '<div class="empty">没有匹配的抓包记录</div>'; return `<div class="table-scroll"><table><thead><tr><th>时间</th><th>方向</th><th>网络类型</th><th>主机</th><th>大小</th><th>协议命令</th><th>协议类型</th><th>协议状态</th></tr></thead><tbody>${rows.map(x => `<tr class="traffic-row ${state.selected?.id === x.id ? 'selected' : ''}" data-id="${x.id}"><td class="mono">${esc(new Date(x.time).toLocaleTimeString([], { hour12: false }))}</td><td><span class="direction ${x.direction === 'request' ? 'request' : x.direction === 'response' ? 'response' : ''}">${esc(x.direction)}</span></td><td>${esc(network(x))}</td><td class="host-cell" title="${esc(x.host)}">${esc(x.host)}</td><td class="mono">${x.size} B</td><td class="command-cell" title="${esc(commandName(x))}">${esc(commandName(x))}</td><td>${esc(protocol(x))}</td><td><span class="status-text" title="${esc(protocolStatus(x))}">${esc(protocolStatus(x) || '未分析')}</span></td></tr>`).join('')}</tbody></table></div>${pager()}`; }
function detailSection(title, value, className = '') { return `<section class="detail-section ${className}"><h3>${esc(title)}</h3><pre>${esc(pretty(value))}</pre></section>`; }
function renderDetail() { const x = state.selected; if (!x) { detail.className = 'detail-empty'; detail.innerHTML = '<span class="detail-glyph">⌁</span><strong>选择一条流量</strong><p>左侧选择记录后查看解密后的 JSON</p>'; return; } detail.className = 'detail-content'; const f = frame(x); if (!state.editPayload) state.editPayload = pretty(f.payload); const side = f.schema_side || (x.direction === 'request' ? 'request' : 'response'); detail.innerHTML = `<div class="detail-head"><div><span class="eyebrow">网络 ${esc(x.direction)} · Sproto ${esc(side)} · ${esc(network(x))}</span><h2>${esc(f.command_name || protocol(x) || '解密报文')}</h2><p>${esc(x.host)} · ${x.size} B · ${esc(new Date(x.time).toLocaleString())}</p></div><div class="detail-actions"><button id="copy-detail" class="quiet" title="复制 JSON">复制</button><button id="reset-json" class="quiet" title="恢复原始解码 JSON">恢复</button></div></div><div class="detail-scroll"><section class="json-editor-section"><div class="editor-head"><div><h3>解密后 JSON</h3><span>命令原生 Sproto ${esc(side)} 构造体</span></div><div class="editor-actions"><button id="format-json" class="quiet">格式化</button><button id="debug-json" class="debug-button" ${x.direction === 'request' && side === 'request' ? '' : 'disabled'}>调试发送</button></div></div><textarea id="json-editor" spellcheck="false" aria-label="解密后的标准 JSON"></textarea><div id="json-debug-status" class="json-debug-status" role="status"></div></section></div>`; const editor = document.querySelector('#json-editor'); editor.value = state.editPayload; editor.oninput = () => { state.editPayload = editor.value; }; document.querySelector('#format-json').onclick = () => { try { editor.value = JSON.stringify(JSON.parse(editor.value), null, 2); state.editPayload = editor.value; setDebugStatus('JSON 格式正确', true); } catch (error) { setDebugStatus(`格式化失败：${error.message}`, false); } }; document.querySelector('#debug-json').onclick = async () => { try { const parsed = JSON.parse(editor.value); const response = await fetch('/api/debug/send', { method: 'POST', body: JSON.stringify({ record_id: x.id, payload: parsed }) }); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || '发送失败'); setDebugStatus(`调试发送成功：${result.command} · ${result.wire_hex.length / 2} 字节`, true); } catch (error) { setDebugStatus(`调试发送失败：${String(error?.message || error || '未知错误')}`, false); } }; document.querySelector('#reset-json').onclick = () => { state.editPayload = pretty(f.payload); renderDetail(); }; document.querySelector('#copy-detail').onclick = () => navigator.clipboard?.writeText(editor.value); }
function setDebugStatus(message, success) { const target = document.querySelector('#json-debug-status'); if (!target) return; target.textContent = message; target.className = `json-debug-status ${success ? 'success' : 'error'}`; }
function renderList() { view.innerHTML = `<div class="list-head"><div><strong>流量</strong><span>${filteredRows().length} / ${state.total}</span></div><span class="live-dot">● 实时</span></div>${table()}`; refreshFilters(); bind(); }
function render() { renderList(); renderDetail(); }
function openRaw(id) { const modal = document.querySelector('#modal'); document.querySelector('#modal-title').textContent = '原始 Message Payload'; document.querySelector('#modal-body').textContent = '正在读取…'; modal.classList.add('open'); fetch(`/api/raw?id=${id}`).then(r => r.ok ? r.text() : Promise.reject()).then(text => { document.querySelector('#modal-body').textContent = text; }).catch(() => { document.querySelector('#modal-body').textContent = '原始报文读取失败'; }); }
function bind() { document.querySelectorAll('.traffic-row').forEach(row => row.onclick = async () => { const summary = state.events.find(x => String(x.id) === row.dataset.id); if (!summary) return; state.selected = summary; state.editPayload = ''; detail.innerHTML = '<div class="detail-empty"><strong>正在加载解密报文…</strong><p>仅加载当前选中记录</p></div>'; try { const response = await fetch(`/api/record?id=${row.dataset.id}`); if (!response.ok) throw new Error(); state.selected = await response.json(); renderDetail(); } catch { detail.innerHTML = '<div class="detail-empty"><strong>详情加载失败</strong><p>请重新选择该记录</p></div>'; } renderList(); }); const newer = document.querySelector('#newer'); const older = document.querySelector('#older'); if (newer) newer.onclick = () => loadPage(state.page - 1); if (older) older.onclick = () => loadPage(state.page + 1); document.querySelectorAll('[data-filter]').forEach(e => e.onchange = () => { state.filters[e.dataset.filter] = e.value; renderList(); }); }
document.querySelector('#filter-search').oninput = e => { state.filters.search = e.target.value; renderList(); };
document.querySelector('#filter-exclude-command').onchange = e => { state.filters.excludeCommand = e.target.value; renderList(); };
document.querySelector('#reset-filters').onclick = () => { state.filters = { search: '', direction: '', network: '', host: '', protocol: '', status: '', excludeCommand: '' }; document.querySelector('#filter-search').value = ''; renderList(); };
document.querySelector('#pause').onclick = event => { state.paused = !state.paused; event.target.textContent = state.paused ? '继续' : '暂停'; };
document.querySelector('#clear').onclick = () => { state.events = []; state.selected = null; state.editPayload = ''; state.total = 0; render(); };
document.querySelector('#clear-history').onclick = async () => { if (!confirm('确定清除全部历史抓包？实时代理不会停止。')) return; const button = document.querySelector('#clear-history'); button.disabled = true; try { const response = await fetch('/api/history/clear', { method: 'POST' }); if (!response.ok) throw new Error(); state.events = []; state.pending = []; state.selected = null; state.editPayload = ''; state.total = 0; state.page = 0; render(); } catch { alert('清除历史抓包失败'); } finally { button.disabled = false; } };
document.querySelector('#modal-close').onclick = () => document.querySelector('#modal').classList.remove('open');
document.querySelector('#modal').onclick = event => { if (event.target.id === 'modal') event.currentTarget.classList.remove('open'); };
function flush() { state.renderTimer = 0; const batch = state.pending.splice(0); if (!batch.length) return; state.total += batch.length; if (state.page === 0) { state.events.push(...batch); if (state.events.length > state.pageSize) state.events.splice(0, state.events.length - state.pageSize); renderList(); } }
const events = new EventSource('/api/events'); events.onopen = () => status.textContent = '● 实时连接'; events.onerror = () => status.textContent = '● 连接断开'; events.onmessage = event => { if (!state.paused) try { state.pending.push(JSON.parse(event.data)); if (!state.renderTimer) state.renderTimer = setTimeout(flush, 250); } catch {} };
loadPage().catch(() => render());
